# Generated by Django 5.2.12 on 2026-03-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('csv', 'CSV'), ('xlsx', 'Excel (XLSX)'), ('xml', 'XML'), ('pdf', 'PDF'), ('txt', 'Texto')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sheet_tab', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_sources', models.ManyToManyField(related_name='reports', to='reports.datasource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='charts/%Y/%m/')),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='Configuração Plotly/Matplotlib serializada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='reports.report')),
            ],
            options={
                'verbose_name': 'Gráfico',
                'verbose_name_plural': 'Gráficos',
            },
        ),
    ]
